### ISSUE TITLE
Can't use input props anymore

### ISSUE THREAD

**Issue by okhomenko** [haoxins/react-flatpickr#252]
Can't pass input props like `placeholder`, `disabled`, `id`, `readonly` anymore

It used to be in 4.0.1

https://github.com/haoxins/react-flatpickr/blob/v4.0.1/lib/datetime-picker.jsx#L166
```tsx
<input {...props} defaultValue={defaultValue} ref={this.handleNodeChange} />
```

now in 4.0.7 it's more restricted
https://github.com/haoxins/react-flatpickr/blob/master/lib/DateTimePicker.tsx#L134
```tsx
<input value={value?.toString()} className={className} defaultValue={defaultValue} ref={handleNodeChange} />
```

**Comment by jasonsyoung** [comment]
argh, let me fix. i removed them to fix a separate issue

**Comment by jasonsyoung** [comment]
ok this should be fixed in 4.0.8

**Comment by okhomenko** [comment]
Still the same

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKFEljgBEUYkAVUJABWDQGsko42XASLoYAWkwAbJmG48oZKlTQQAdgGd4AQTBg4AXjgAKAJSGAfHADeVOHCIwArlDVwAPI2ZsQnefzgwGTQkAAsIKQATfgMAIli4AHoLKgBfKiA

<img width="832" alt="Image" src="https://github.com/user-attachments/assets/1ec497a3-f623-4d10-9fc6-632166bcc73c" />

My guess is we need to add here `extends of Input props`
https://github.com/haoxins/react-flatpickr/blob/master/types/react-flatpickr.d.ts#L15

Similar to how it's done here
https://www.npmjs.com/package/@types/react-flatpickr

**Comment by jasonsyoung** [comment]
@okhomenko thank you, I will add that today

**Comment by jasonsyoung** [comment]
@okhomenko i have pushed a new release with this fix!

**Comment by okhomenko** [comment]
@jasonsyoung appreciate it. Now TS errors are gone.
